### ISSUE TITLE
On Create Cluster, can't unselect an image after selecting it

### ISSUE THREAD

**Issue by JuanValencia** [inercia/vscode-k3d#7]
I select a node image.  Then after changing my mind, I got to select a different one, there are none listed.

I expect I could see the original list.

**Comment by inercia** [comment]
Have you tried to clear the text box? I think the dropdown list will only list images that match the contents of the text box, so you should probably clear it for getting a full list of images...

**Comment by inercia** [comment]
Closed because of inactivity. Please reopen if you want.
